
spring:
  #数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.132.172.154:3306/kyb?characterEncoding=utf-8&useSSL=true&allowMultiQueries=true #&allowMultiQueries=true:允许mybatis xml 同时操作多条sql语句
    username: root
    password: nbrt123
  #模块名称
  application:
    name: home-care
#  #时间格式
#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss
#    time-zone: GMT+8

  cloud:
    #nacos
    nacos:
      #      server-addr: 127.0.0.1:8848
      server-addr: 101.132.172.154:8848
  #时间戳统一转换
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  #redis配置
  redis:
    host: 101.132.172.154
    port: 6379
    password: nbrt123
  main:
    allow-bean-definition-overriding: true


#模块端口
server:
  port: 9000
#mybatis-plus配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
      id-type: auto
logging:
  register-shutdown-hook: