server:
  port: 8809
spring:
  application:
    name: mall-service
  #数据库配置
  datasource:
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.132.172.154:3306/kyb?characterEncoding=utf-8&useSSL=true&serverTimezone=UTC&allowMultiQueries=true #&allowMultiQueries=true:允许mybatis xml 同时操作多条sql语句
    username: root
    password: nbrt123
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # redis
  redis:
    host: 101.132.172.154
    port: 6379
    password: nbrt123
  servlet:
    # 文件上传
    multipart:
      enabled: true
      # 单个文件大小
      max-file-size: 10MB
      # 设置总上传的数据大小 （批量）
      max-request-size: 50MB
      # 当文件达到多少时进行磁盘写入
      file-size-threshold: 20MB
      # 设置临时目录
      location: E://data//temp
  cloud:
    #nacos
    nacos:
      server-addr: 101.132.172.154:8848
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

#配置缓存相关
cache:
  default:
    expire-time: 200
  user:
    expire-time: 180
    name: test

aliyun:
  oss:
    file:
      endpoint: oss-cn-beijing.aliyuncs.com
      accessKeyId: LTAI5tDSjPDfPmkiYbBSVg11
      accessKeySecret: gZH0mF25FTEzJEsyRdeasso7mU1qph
      bucketName: shoolsafe